// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUwI6enS8MIpjAyWNNNsfQTOCiaM2HEKY',
    appId: '1:715025222490:web:572dafd177cf299d254163',
    messagingSenderId: '715025222490',
    projectId: 'topo-app-30336',
    authDomain: 'topo-app-30336.firebaseapp.com',
    storageBucket: 'topo-app-30336.firebasestorage.app',
    measurementId: 'G-Y3JJTX6NHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHVRM-imdxAx0USpmm3G2JiZQjipIgULU',
    appId: '1:715025222490:android:6558f11ba9b84abb254163',
    messagingSenderId: '715025222490',
    projectId: 'topo-app-30336',
    storageBucket: 'topo-app-30336.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt8A2m8cqZbyBjtSYOrD8CiTQ3hk-Aoms',
    appId: '1:715025222490:ios:435f07f8d3825366254163',
    messagingSenderId: '715025222490',
    projectId: 'topo-app-30336',
    storageBucket: 'topo-app-30336.firebasestorage.app',
    iosBundleId: 'com.example.topoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt8A2m8cqZbyBjtSYOrD8CiTQ3hk-Aoms',
    appId: '1:715025222490:ios:435f07f8d3825366254163',
    messagingSenderId: '715025222490',
    projectId: 'topo-app-30336',
    storageBucket: 'topo-app-30336.firebasestorage.app',
    iosBundleId: 'com.example.topoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUwI6enS8MIpjAyWNNNsfQTOCiaM2HEKY',
    appId: '1:715025222490:web:0730d4090d1e3594254163',
    messagingSenderId: '715025222490',
    projectId: 'topo-app-30336',
    authDomain: 'topo-app-30336.firebaseapp.com',
    storageBucket: 'topo-app-30336.firebasestorage.app',
    measurementId: 'G-SB3RZN3BGW',
  );
}